server:
  port: 8080
  tomcat:
    max-swallow-size: -1 #设置tomcat的最大吞吐量
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS #返回异常错误信息
  servlet:
    context-path: /quick-system
  compression:
    enabled: true  #Http包压缩功能
    min-response-size: 1024 #压缩阈值
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/* #指定要压缩的类型

spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  mvc:
    static-path-pattern: /**
    #Spring Boot 2.6+后映射匹配的默认策略已从AntPathMatcher更改为PathPatternParser,需要手动指定为ant-path-matcher
    pathmatch: #不加swagger读取不了控制器
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # 主库数据源
    url: jdbc:mysql://172.20.20.19:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Ntdh@123
    druid:
      stat-view-servlet:
        enabled: true
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true

#  autoconfigure:
#    exclude:
#swagger
knife4j:
  #开启增强配置
  enable: true
  #开启生产环境屏蔽
  production: false
  basic:
    enable: false
    username: zhoujian
    password: 1234

